import { Application } from 'express';
import { accountsRouter } from '../modules/accounts/accounts.router.js';
import { casesRouter } from '../modules/cases/cases.router.js';
import { candidatesRouter } from '../modules/candidates/candidates.router.js';
import { evaluationsRouter } from '../modules/evaluations/evaluations.router.js';
import { interviewerRouter } from '../modules/evaluations/interviewer.router.js';
import { questionsRouter } from '../modules/questions/questions.router.js';
import { caseCriteriaRouter } from '../modules/caseCriteria/caseCriteria.router.js';
import { analyticsRouter } from '../modules/analytics/analytics.router.js';
import { healthRouter } from '../shared/health.router.js';
import { authRouter } from '../modules/auth/auth.router.js';
import { demoRouter } from '../modules/demo/demo.router.js';
import { workstreamsRouter } from '../modules/workstreams/workstreams.router.js';
import { initiativesRouter } from '../modules/initiatives/initiatives.router.js';
import { approvalsRouter } from '../modules/approvals/approvals.router.js';
import { participantsRouter } from '../modules/participants/participants.router.js';
import { financialsRouter } from '../modules/financials/financials.router.js';
import { snapshotsRouter } from '../modules/snapshots/snapshots.router.js';
import { initiativeLogsRouter } from '../modules/logs/initiativeLogs.router.js';

export const registerAppRoutes = (app: Application) => {
  // TODO: add middleware for authentication and request logging
  app.use('/health', healthRouter);
  app.use('/accounts', accountsRouter);
  app.use('/auth', authRouter);
  app.use('/cases', casesRouter);
  app.use('/candidates', candidatesRouter);
  app.use('/evaluations', evaluationsRouter);
  app.use('/interviewer', interviewerRouter);
  app.use('/questions', questionsRouter);
  app.use('/case-criteria', caseCriteriaRouter);
  app.use('/analytics', analyticsRouter);
  app.use('/workstreams', workstreamsRouter);
  app.use('/initiatives', initiativesRouter);
  app.use('/approvals', approvalsRouter);
  app.use('/participants', participantsRouter);
  app.use('/financials', financialsRouter);
  app.use('/snapshots', snapshotsRouter);
  app.use('/initiative-logs', initiativeLogsRouter);
  app.use('/demo', demoRouter);
};
